name: bakurubey_tharujama
description: A Flutter project for iOS and Android devices to easily access the digitized translation of the late Sheikh Bakurube (May Allah have mercy on him).

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  quran: ^1.1.2
  expandable: ^5.0.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/surah_table.json
    - assets/juz_table.json

  fonts:
    - family: Uthmanic
      fonts:
        - asset: fonts/UthmanicHafs_V20.ttf

    - family: Midhili
      fonts:
        - asset: fonts/midhilibold.ttf

    - family: Elaaf
      fonts:
        - asset: fonts/Mv_Elaaf_Normal.otf

    - family: Waheed
      fonts:
        - asset: fonts/MVWaheed.otf

    - family: Arslan
      fonts:
        - asset: fonts/ArslanWessamA.ttf

    - family: Janna
      fonts:
        - asset: fonts/JannaLTBold.ttf

    - family: Diwani
      fonts:
        - asset: fonts/Diwanltr.ttf

    - family: Typewriter
      fonts:
        - asset: fonts/mvtyper.ttf
        - asset: fonts/mvtypebold.ttf

    - family: TypewriterSB
      fonts:
        - asset: fonts/mvtypewritersb.ttf

    - family: Utheemu
      fonts:
        - asset: fonts/mvutheemuBOLD.ttf
        - asset: fonts/mvutheemuREGULAR.ttf
